config/routes.rb
Rails.application.routes.draw do
  resources :departments
  root to: "products#index"
  resources :products, only: [:new, :create, :destroy, :edit, :update]

  get "products/find" => "products#search", as: :find_product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :amount, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    products = Product.all
    @products_with_this_department = products.where(department_id: @department)
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @products = Product.all
    @departments = Department.all
    respond_to do |format|
      if(!@products.find_by_department_id @department.id)
        @department.destroy
        format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
        format.json { head :no_content }
      else
        @message = "Department can't be destroyed because have some products linked them"
        format.html { render :index}
        format.json { render json: @message, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only:[:edit, :update, :destroy]

  def index
    @products = Product.all
    @best_offer = Product.order(price: :desc).limit 1
  end

  def new
    @product = Product.new
    @departments = Department.all
  end

  def create
    @product = Product.new product_params
    if(@product.save)
      flash[:notice] = "Product successfully created"
      redirect_to new_product_path
    else
      @departments = Department.all
      render :new
    end
  end

  def edit
    @departments = Department.all
  end

  def search
    @name = params[:name]
    @products = Product.where "name like ?",  "%#{@name}%"
  end

  def update
    if @product.update product_params
      flash[:notice] = "Product successfully updated"
      redirect_to root_url
    else
      render :edit
    end
  end

  def destroy
    if @product.destroy
      flash[:notice] = "Product successfully removed"
    else
      flash[:notice] = "This operation can't be done"
    end
    redirect_to root_url
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :amount, :price, :department_id)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/departments/_form.html.erb
<div class="form-background">
  <div class="form-content">
    <%= form_with(model: @department, local: true) do |form| %>
      <% if @department.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@department.errors.count, "error") %> prohibited this department from being saved:</h2>

          <ul>
          <% @department.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row">
        <div class="col-sm-12">
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, class: 'form-control' %>
          </div>
        </div>
      </div>

        <%= form.submit name, class: "btn btn-success" %>
        <%= link_to "Cancel", departments_path, class: "btn btn-primary " %>
    <% end %>
  </div>
</div>

app/views/departments/_notices.haml
- if @message
  .alert.alert-danger{role: "alert"}
    = @message

app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render partial:'form', department: @department, locals: {name: "Update department"} %>

app/views/departments/index.html.erb
<%= render partial: 'notices' %>
<h1>Departments</h1>
<div class="container-fluid">
  <div class="table-responsive">
    <table class="table table-striped table-dark text-center">
      <thead>
        <tr>
          <th>Name</th>
          <th>Created at</th>
          <th>Updated at</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @departments.each do |department| %>
          <tr>
            <td><%= department.name %></td>
            <td><%= department.created_at %></td>
            <td><%= department.updated_at %></td>
            <td>
              <div class="ajust-buttons">
                <%= link_to 'Show', department, class: 'btn btn-default' %>
                <p class="separator">|</p>
                <%= link_to 'Edit', edit_department_path(department), class: 'btn btn-info' %>
                <p class="separator">|</p>
                <%= link_to 'Destroy', department, method: :delete, data: { confirm: "Are you sure do you want to remove #{department.name}?" }, class: 'btn btn-danger' %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'New Department', new_department_path, class: "btn btn-default"%>
</div>

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render partial:'form', department: @department, locals: {name: "Create a department"} %>

app/views/departments/show.html.erb
<h1><%= @department.name %></h1>

<div class="container-fluid">
  <div class="table-responsive">
    <table class="table table-striped table-dark text-center">
      <thead>
      <tr>
        <th>Name</th>
        <th>Created at</th>
        <th>Updated at</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @products_with_this_department.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.created_at %></td>
          <td><%= product.updated_at %></td>
          <td>
            <div class="ajust-buttons">
              <%= link_to 'Edit', edit_product_path(product), class: 'btn btn-info' %>
              <p class="separator">|</p>
              <%= link_to 'Destroy', product, method: :delete, data: { confirm: "Are you sure do you want to remove #{product.name}?" }, class: 'btn btn-danger' %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'Edit', edit_department_path(@department), class: 'btn btn-default' %> |
<%= link_to 'Back', departments_path, class: 'btn btn-default'%>

app/views/layouts/_navbar.html.erb
<%= nav_bar brand: "Retail Store 1.0", brand_link: root_url do %>
  <%= menu_group do %>
    <%= menu_item "Create a new product", new_product_path %>
    <%= menu_item "Departments", departments_path %>
  <% end %>

  <%= form_tag find_product_path, method: :get, class:"navbar-form navbar-right" do %>
    <div class="form-group">
      <%= text_field_tag :name, @name, class:"form-control" %>
      <%= button_to "Search", nil, class:"btn btn-default" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RetailStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="backgroundColor">
    <%= render partial: "layouts/navbar" %>
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-success" role="alert">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_formNewEdit.haml
.form-background
  .form-content
    = form_for @product do |form|
      .row
        .col-sm-12
          .form-group.errorDisplay
            = form.label :name
            = form.text_field :name, class: "form-control"
      .row
        .col-sm-12
          .form-group.errorDisplay
            = form.label :description
            = form.text_area :description, class: "form-control", rows: 4
      .row
        .col-sm-12
          .form-group.errorDisplay
            = form.label :amount
            = form.number_field :amount, min: 1, step: 1, class: "form-control"
      .row
        .col-sm-12
          .form-group.errorDisplay
            = form.label :price
            = form.number_field :price, min: 1, step: 0.01, class: "form-control"
      .row
        .col-sm-12
          .form-group.errorDisplay
            = form.label :department
            = form.collection_select :department_id, @departments, :id, :name, {}, class: 'form-control'
      = form.submit name, class: "btn btn-success"
      = link_to "Cancel", root_url, class: "btn btn-primary "

app/views/products/_notices.haml
- @product.errors.full_messages.each do |msg|
  .alert.alert-danger{role: "alert"}
    = msg

app/views/products/_table.haml
- @products.each do |product|
  %tr
    %td= product.name
    %td= product.description
    %td= Department.find(product.department_id).name
    %td= product.price
    %td= product.amount
    %td
      .ajust-buttons
        = link_to "Edit", edit_product_path(product), class:"btn btn-info "
        %p.separator
        = button_to "Remove", product, method: :delete, class:"btn btn-danger", data: {confirm: "Are you sure do you want to remove #{product.name}?"}

app/views/products/edit.html.haml
= render partial: "notices"
%h1 Edit a Product
= render partial: "formNewEdit", locals: {name: "Update product"}

app/views/products/index.haml
%h1 Products
.table-responsive
  %table.table.table-striped.table-dark.text-center
    %thead
      %tr
        %th Name
        %th Description
        %th Department
        %th Price
        %th Amount
        %th
    %tbody
      = render partial: 'table'

app/views/products/new.haml
= render partial: "notices"
%h1 Create a new product
= render partial:'formNewEdit', locals: {name: "Create a new product"}

app/views/products/search.haml
%h1 Products find
.table-responsive
  %table.table.table-striped.table-dark.text-center
    %thead
      %tr
        %th Name
        %th Description
        %th Department
        %th Price
        %th Amount
        %th{colspan: "2"}
    %tbody
      = render partial: 'table'